"""Prospectively locked BTC five-minute public observation pilot, never trading."""

import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
import json
from pathlib import Path
import shutil
import threading
import time

from .acquisition import PublicPolymarketAcquirer, UrllibJsonTransport, utc_now, utc_text
from .bundle import normalize_bundle, store_raw_bundle, store_raw_slug_resolution, store_raw_settlement
from .contracts import ContractError, payload_hash, verify_artifact_hash
from .market_stream import collect_market_stream, stream_plan, verify_stream_log
from .binance_source import _time
from .settlement import normalize_settlement

SCHEMA = "qcrl.btc_5m_rolling_pilot.v2"
SOURCE = "https://data.chain.link/streams/btc-usd-twap-60s-streams"
DESCRIPTION = ('This market will resolve to "Up" if the time-weighted average price (TWAP) of Bitcoin, generated by Chainlink, of the time range specified in the title is greater than or equal to the price at the beginning of that range. Otherwise, it will resolve to "Down".\n'
               'The resolution source for this market is information from Chainlink, specifically the BTC/USD TWAP data stream available at https://data.chain.link/streams/btc-usd-twap-60s-streams.\n'
               'Please note that this market is about the price according to the TWAP Chainlink data stream for the asset pair BTC/USD, not according to any other sources or spot markets.')


def pilot_plan(first_start, count=6, *, now=None, profiling=False, resilient=False, deferred=False, receive_path=False,
               receive_policy="v1"):
    now = now or utc_now()
    if type(first_start) is not int or first_start % 300:
        raise ContractError("first start must be an aligned epoch integer")
    if type(count) is not int or not 1 <= count <= 24:
        raise ContractError("pilot requires 1..24 markets")
    if first_start < now.timestamp() + 45:
        raise ContractError("declare pilot at least 45 seconds before first market")
    if type(profiling) is not bool:
        raise ContractError("profiling must be boolean")
    if type(resilient) is not bool:
        raise ContractError("resilient must be boolean")
    if type(deferred) is not bool:
        raise ContractError("deferred must be boolean")
    if type(receive_path) is not bool or (receive_path and not (profiling and deferred)):
        raise ContractError("receive path requires profiling and deferred verification")
    if receive_policy not in ("v1", "v2") or (not receive_path and receive_policy != "v1"):
        raise ContractError("receive policy requires an explicit supported receive path")
    plan = {"schema_version": SCHEMA, "declared_at_utc": utc_text(now),
            "market_starts": [first_start + 300 * i for i in range(count)],
            "resolution_source": SOURCE, "description_sha256": payload_hash(DESCRIPTION),
            "max_spool_bytes": 2 * 1024**3, "minimum_free_bytes": 1024**3,
            "orders_authorized": False, "continuous_coverage_proven": False}
    if profiling:
        from copy import deepcopy
        from .stream_profiling import POLICY
        plan["schema_version"] = "qcrl.btc_5m_rolling_pilot.v3"
        plan["profiling"] = deepcopy(POLICY)
    if resilient:
        from copy import deepcopy
        from .stream_resilience import POLICY
        plan["schema_version"] = "qcrl.btc_5m_rolling_pilot.v4"
        plan["resilience"] = deepcopy(POLICY)
    if deferred or resilient:
        plan["schema_version"] = "qcrl.btc_5m_rolling_pilot.v4"
        plan["verification_phase"] = "after_all_capture_workers"
    if receive_path:
        from copy import deepcopy
        from .receive_path import policy_for
        plan["schema_version"] = "qcrl.btc_5m_rolling_pilot.v6" if receive_policy == "v2" else "qcrl.btc_5m_rolling_pilot.v5"
        plan["receive_path"] = policy_for(receive_policy)
    plan["plan_sha256"] = payload_hash(plan)
    return plan


def validate_plan(plan):
    verify_artifact_hash(plan, "plan_sha256", "rolling pilot")
    starts = plan.get("market_starts")
    if not isinstance(starts, list) or not starts:
        raise ContractError("pilot has no market starts")
    declared = datetime.fromisoformat(plan["declared_at_utc"].replace("Z", "+00:00"))
    from .receive_path import policy_version
    version = policy_version(plan["receive_path"]) if "receive_path" in plan else "v1"
    if declared.tzinfo is None or pilot_plan(starts[0], len(starts), now=declared,
                                          profiling="profiling" in plan, resilient="resilience" in plan,
                                          deferred="verification_phase" in plan, receive_path="receive_path" in plan,
                                          receive_policy=version) != plan:
        raise ContractError("pilot differs from bounded public-only policy")
    return plan


def check_market(bundle, start, plan):
    market = normalize_bundle(bundle)["market_contract"]
    expected = "btc-updown-5m-" + str(start)
    if market["identity"]["slug"] != expected:
        raise ContractError("discovered slug differs from locked market")
    from .receive_path import policy_version
    spec = stream_plan(bundle, max_frames=1000000, segmented=True,
                       profiling="profiling" in plan, resilient="resilience" in plan,
                       receive_path="receive_path" in plan,
                       source_plan_sha256=plan["plan_sha256"] if "receive_path" in plan else None,
                       receive_policy=policy_version(plan["receive_path"]) if "receive_path" in plan else "v1")
    if (datetime.fromisoformat(spec["event_start_at_utc"].replace("Z", "+00:00")).timestamp() != start
            or datetime.fromisoformat(spec["event_end_at_utc"].replace("Z", "+00:00")).timestamp() != start + 300):
        raise ContractError("explicit interval differs from locked window")
    terms = market["terms"]
    if (not terms["question"].startswith("Bitcoin Up or Down - ")
            or terms["resolution_source"] != plan["resolution_source"]
            or payload_hash(terms["description"]) != plan["description_sha256"]):
        raise ContractError("BTC resolution terms changed; manual review required")
    state = market["state"]
    if any(state[k] is not v for k, v in (("active", True), ("closed", False),
                                         ("order_book_enabled", True), ("accepting_orders", True))):
        raise ContractError("market is not open for public book observation")
    return spec


def persist(path, artifact):
    """Exclusive durable artifact; a previous result is never overwritten."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8") as handle:
        json.dump(artifact, handle, sort_keys=True, indent=2)
        handle.flush()
        import os
        os.fsync(handle.fileno())


def spool_ok(root, plan):
    return (sum(p.stat().st_size for p in root.rglob("*") if p.is_file()) < plan["max_spool_bytes"] - 2 * 256 * 1024**2
            and shutil.disk_usage(root).free >= plan["minimum_free_bytes"])


def followup_label(start, observed_epoch):
    if observed_epoch < start + 300:
        return "bounded_followup_before_close"
    if observed_epoch < start + 420:
        return "bounded_followup_after_close"
    return "postclose_120s"


def observe_window(start, plan, root):
    """Keep HTTP checkpoints off the socket reader; bound discovery and follow-up."""
    directory = root / str(start)
    directory.mkdir(exist_ok=True)
    result = {"market_start": start, "orders_authorized": False,
              "continuous_coverage_proven": False, "metadata_checkpoints": []}
    acquirer = PublicPolymarketAcquirer(UrllibJsonTransport(timeout_seconds=5))
    done = threading.Event()
    checkpoint_thread = None
    try:
        if utc_now().timestamp() >= start + 30:
            result["status"] = "missed_discovery_window"
            return
        bundle = None
        attempts = []
        while utc_now().timestamp() < start + 15:
            try:
                resolution = acquirer.resolve_market_slug("btc-updown-5m-" + str(start), "market")
                store_raw_slug_resolution(resolution, directory)
                bundle = acquirer.acquire_market_bundle(resolution["resolved_market_id"])
                store_raw_bundle(bundle, directory)
                spec = check_market(bundle, start, plan)
                break
            except ContractError:
                raise  # Terms/state mismatch is not a transient discovery failure.
            except Exception as exc:
                attempts.append({"at_utc": utc_text(utc_now()), "error_type": type(exc).__name__})
                time.sleep(5)
        result["discovery_failures"] = attempts
        if bundle is None or utc_now().timestamp() >= start + 30:
            result["status"] = "missed_discovery_window"
            return
        result["capture_started_at_utc"] = utc_text(utc_now())
        result["late_start"] = utc_now().timestamp() > start
        result["raw_bundle_sha256"] = bundle["bundle_sha256"]
        market_id = bundle["market_id_requested"]

        def checkpoint(label):
            try:
                artifact = acquirer.acquire_market_settlement(market_id)
                path = store_raw_settlement(artifact, directory)
                result["metadata_checkpoints"].append({"label": label, "file": path.name})
            except Exception as exc:
                result["metadata_checkpoints"].append({"label": label, "error_type": type(exc).__name__})

        def periodic():
            while not done.wait(60):
                checkpoint("periodic")

        checkpoint_thread = threading.Thread(target=periodic, daemon=True)
        checkpoint_thread.start()
        log = directory / "stream"
        try:
            result["stream_summary"] = collect_market_stream(bundle, spec, log)
            if "verification_phase" not in plan:
                result["verification"] = verify_stream_log(log)
            result["status"] = "observed_" + result["stream_summary"]["status"]
        except Exception as exc:
            result["status"] = "failed"
            result["error_type"], result["error"] = type(exc).__name__, str(exc)[:300]
            if "verification_phase" not in plan:
                try:
                    result["verification"] = verify_stream_log(log)
                except Exception as verification_error:
                    result["verification_error_type"] = type(verification_error).__name__
        finally:
            done.set()
            checkpoint_thread.join()
            checkpoint("final")
            # Independent of reader success; wait to the actual locked boundary.
            while utc_now().timestamp() < start + 420:
                time.sleep(max(0, min(1, start + 420 - utc_now().timestamp())))
            checkpoint(followup_label(start, utc_now().timestamp()))
    except Exception as exc:
        result["status"] = "failed"
        result["error_type"] = type(exc).__name__
        result["error"] = str(exc)[:300]
        if "verification_phase" not in plan and (directory / "stream.ndjson").exists():
            try:
                result["verification"] = verify_stream_log(directory / "stream.ndjson")
            except Exception as verification_error:
                result["verification_error_type"] = type(verification_error).__name__
    finally:
        done.set()
        if checkpoint_thread is not None:
            checkpoint_thread.join()
        result["finished_at_utc"] = utc_text(utc_now())
        result["result_sha256"] = payload_hash(result)
        persist(directory / ("capture_result.json" if "verification_phase" in plan else "result.json"), result)
        print(json.dumps(result), flush=True)


def run_pilot(plan, root):
    validate_plan(plan)
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    # Exclusive declaration prevents replaying a cohort after a restart.
    persist(root / "pilot.json", plan)
    futures = []
    with ThreadPoolExecutor(max_workers=2) as workers:
        for start in plan["market_starts"]:
            while utc_now().timestamp() < start - 30:
                time.sleep(max(0, min(1, start - 30 - utc_now().timestamp())))
            if not spool_ok(root, plan):
                raise ContractError("spool/free-space budget exhausted; stop without deleting evidence")
            futures.append(workers.submit(observe_window, start, plan, root))
        for future in futures:
            future.result()
    if "verification_phase" in plan:
        finalize_cases(plan, root)
    return cohort_health(plan, root)


def finalize_cases(plan, root):
    """Only call after all observation workers have joined; never overwrite."""
    for start in plan["market_starts"]:
        directory = Path(root) / str(start)
        capture = json.loads((directory / "capture_result.json").read_text())
        verify_artifact_hash(capture, "result_sha256", "capture result")
        result = dict(capture)
        result["capture_result_sha256"] = capture["result_sha256"]
        try:
            result["verification"] = verify_stream_log(directory / "stream")
        except Exception as exc:
            result["verification_error_type"] = type(exc).__name__
        result["verified_at_utc"] = utc_text(utc_now())
        result.pop("result_sha256")
        result["result_sha256"] = payload_hash(result)
        persist(directory / "result.json", result)


def cohort_health(plan, root):
    cases, problems = [], []
    for start in plan["market_starts"]:
        path = Path(root) / str(start) / "result.json"
        if not path.exists():
            problems.append({"start": start, "reason": "missing_result"})
            continue
        case = json.loads(path.read_text())
        verify_artifact_hash(case, "result_sha256", "pilot result")
        if "verification_phase" in plan:
            capture = json.loads((path.parent / "capture_result.json").read_text())
            verify_artifact_hash(capture, "result_sha256", "capture result")
            derived = {k: v for k, v in case.items() if k not in
                       ("verification", "verification_error_type", "verified_at_utc", "capture_result_sha256", "result_sha256")}
            if (case.get("capture_result_sha256") != capture["result_sha256"] or
                    derived != {k: v for k, v in capture.items() if k != "result_sha256"}):
                raise ContractError("final result differs from immutable capture result")
        summary, verification = case.get("stream_summary", {}), case.get("verification", {})
        verified_tokens = set()
        try:
            actual = verify_stream_log(Path(root) / str(start) / "stream")
            raw_path = next((Path(root) / str(start)).glob("market-[0-9]*.json"))
            raw = json.loads(raw_path.read_text())
            if raw["bundle_sha256"] != case.get("raw_bundle_sha256") or actual != verification:
                raise ContractError("case verification/source differs from retained evidence")
            if (actual.get("header_spec") != check_market(raw, start, plan)
                    or actual.get("terminal_summary") != summary
                    or actual["frames"] != summary.get("frames")
                    or actual["book_snapshot_assets_by_connection"] != summary.get("book_snapshot_assets_by_connection")):
                raise ContractError("retained stream differs from pinned source or result summary")
            verified_tokens = {o["token_id"] for o in normalize_bundle(raw)["market_contract"]["outcomes"]}
        except Exception:
            verification = {}
        complete = (case.get("status") == "observed_lifecycle_stop"
                    and summary.get("status") == "lifecycle_stop"
                    and verification.get("session_end_present") is True
                    and verification.get("manifest_present") is True
                    and not case.get("late_start", True))
        if complete:
            complete = (_time(verification["first_received_at_utc"]).timestamp() <= start
                        and _time(verification["last_received_at_utc"]).timestamp() >= start + 330)
        checkpoints = case.get("metadata_checkpoints", [])
        if any("error_type" in c for c in checkpoints) or not all(any(c.get("label") == label and "file" in c for c in checkpoints) for label in ("final", "postclose_120s")):
            complete = False
        for checkpoint in checkpoints:
            if "file" not in checkpoint:
                continue
            try:
                filename = checkpoint["file"]
                if Path(filename).name != filename:
                    raise ContractError("invalid checkpoint filename")
                artifact = json.loads((Path(root) / str(start) / filename).read_text())
                verify_artifact_hash(artifact, "settlement_sha256", "checkpoint")
                settlement = normalize_settlement(artifact)
                if settlement["market_id"] != raw["market_id_requested"]:
                    complete = False
                if checkpoint["label"] == "postclose_120s" and _time(artifact["observations"]["gamma_market"]["observed_at_utc"]).timestamp() < start + 420:
                    complete = False
            except Exception:
                complete = False
        if any(set(tokens) != verified_tokens for tokens in summary.get("book_snapshot_assets_by_connection", {}).values()):
            complete = False
        if not summary.get("book_snapshot_assets_by_connection"):
            complete = False
        cases.append({"market_start": start, "status": case.get("status"), "lifecycle_completed": complete,
                      "connections": summary.get("connections"),
                      "reconnected": summary.get("connections", 0) > 1,
                      "continuous_coverage_proven": False})
        if not complete:
            problems.append({"start": start, "reason": "incomplete_capture_or_checkpoints"})
    report = {"schema_version": "qcrl.stream_cohort_health.v1", "expected": len(plan["market_starts"]),
              "completed": sum(c["lifecycle_completed"] for c in cases), "cases": cases,
              "problems": problems, "healthy": not problems, "orders_authorized": False,
              "continuous_coverage_proven": False}
    report["health_sha256"] = payload_hash(report)
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    declare = sub.add_parser("declare")
    declare.add_argument("--first-start", type=int, required=True)
    declare.add_argument("--markets", type=int, default=6)
    declare.add_argument("--output", required=True)
    declare.add_argument("--profile", action="store_true")
    declare.add_argument("--resilient", action="store_true")
    declare.add_argument("--defer-verification", action="store_true")
    declare.add_argument("--receive-path", action="store_true")
    declare.add_argument("--receive-policy", choices=("v1", "v2"), default="v1")
    run = sub.add_parser("run")
    run.add_argument("plan")
    run.add_argument("--root", required=True)
    args = parser.parse_args()
    if args.command == "declare":
        plan = pilot_plan(args.first_start, args.markets, profiling=args.profile,
                          resilient=args.resilient, deferred=args.defer_verification, receive_path=args.receive_path,
                          receive_policy=args.receive_policy)
        persist(args.output, plan)
        print(json.dumps(plan, indent=2))
    else:
        health = run_pilot(json.loads(Path(args.plan).read_text()), args.root)
        persist(Path(args.root) / "health.json", health)
        print(json.dumps(health, indent=2))
        if not health["healthy"]:
            raise SystemExit(1)


if __name__ == "__main__":
    main()
