"""Prospectively locked BTC five-minute public observation pilot, never trading."""

import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
import json
from pathlib import Path
import shutil
import threading
import time

from .acquisition import PublicPolymarketAcquirer, UrllibJsonTransport, utc_now, utc_text
from .bundle import normalize_bundle, store_raw_bundle, store_raw_slug_resolution, store_raw_settlement
from .contracts import ContractError, payload_hash, verify_artifact_hash
from .market_stream import collect_market_stream, stream_plan, verify_stream_log

SCHEMA = "qcrl.btc_5m_rolling_pilot.v1"
SOURCE = "https://data.chain.link/streams/btc-usd-twap-60s-streams"
DESCRIPTION = ('This market will resolve to "Up" if the time-weighted average price (TWAP) of Bitcoin, generated by Chainlink, of the time range specified in the title is greater than or equal to the price at the beginning of that range. Otherwise, it will resolve to "Down".\n'
               'The resolution source for this market is information from Chainlink, specifically the BTC/USD TWAP data stream available at https://data.chain.link/streams/btc-usd-twap-60s-streams.\n'
               'Please note that this market is about the price according to the TWAP Chainlink data stream for the asset pair BTC/USD, not according to any other sources or spot markets.')


def pilot_plan(first_start, count=6, *, now=None):
    now = now or utc_now()
    if type(first_start) is not int or first_start % 300:
        raise ContractError("first start must be an aligned epoch integer")
    if type(count) is not int or not 1 <= count <= 24:
        raise ContractError("pilot requires 1..24 markets")
    if first_start < now.timestamp() + 45:
        raise ContractError("declare pilot at least 45 seconds before first market")
    plan = {"schema_version": SCHEMA, "declared_at_utc": utc_text(now),
            "market_starts": [first_start + 300 * i for i in range(count)],
            "resolution_source": SOURCE, "description_sha256": payload_hash(DESCRIPTION),
            "max_spool_bytes": 2 * 1024**3, "minimum_free_bytes": 1024**3,
            "orders_authorized": False, "continuous_coverage_proven": False}
    plan["plan_sha256"] = payload_hash(plan)
    return plan


def validate_plan(plan):
    verify_artifact_hash(plan, "plan_sha256", "rolling pilot")
    starts = plan.get("market_starts")
    if not isinstance(starts, list) or not starts:
        raise ContractError("pilot has no market starts")
    declared = datetime.fromisoformat(plan["declared_at_utc"].replace("Z", "+00:00"))
    if declared.tzinfo is None or pilot_plan(starts[0], len(starts), now=declared) != plan:
        raise ContractError("pilot differs from bounded public-only policy")
    return plan


def check_market(bundle, start, plan):
    market = normalize_bundle(bundle)["market_contract"]
    expected = "btc-updown-5m-" + str(start)
    if market["identity"]["slug"] != expected:
        raise ContractError("discovered slug differs from locked market")
    spec = stream_plan(bundle)
    if (datetime.fromisoformat(spec["event_start_at_utc"].replace("Z", "+00:00")).timestamp() != start
            or datetime.fromisoformat(spec["event_end_at_utc"].replace("Z", "+00:00")).timestamp() != start + 300):
        raise ContractError("explicit interval differs from locked window")
    terms = market["terms"]
    if (not terms["question"].startswith("Bitcoin Up or Down - ")
            or terms["resolution_source"] != plan["resolution_source"]
            or payload_hash(terms["description"]) != plan["description_sha256"]):
        raise ContractError("BTC resolution terms changed; manual review required")
    state = market["state"]
    if any(state[k] is not v for k, v in (("active", True), ("closed", False),
                                         ("order_book_enabled", True), ("accepting_orders", True))):
        raise ContractError("market is not open for public book observation")
    return spec


def persist(path, artifact):
    """Exclusive durable artifact; a previous result is never overwritten."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8") as handle:
        json.dump(artifact, handle, sort_keys=True, indent=2)
        handle.flush()
        import os
        os.fsync(handle.fileno())


def spool_ok(root, plan):
    return (sum(p.stat().st_size for p in root.rglob("*") if p.is_file()) < plan["max_spool_bytes"] - 2 * 134217728
            and shutil.disk_usage(root).free >= plan["minimum_free_bytes"])


def observe_window(start, plan, root):
    """Keep HTTP checkpoints off the socket reader; bound discovery and follow-up."""
    directory = root / str(start)
    directory.mkdir(exist_ok=True)
    result = {"market_start": start, "orders_authorized": False,
              "continuous_coverage_proven": False, "metadata_checkpoints": []}
    acquirer = PublicPolymarketAcquirer(UrllibJsonTransport(timeout_seconds=5))
    done = threading.Event()
    checkpoint_thread = None
    try:
        if utc_now().timestamp() >= start + 30:
            result["status"] = "missed_discovery_window"
            return
        bundle = None
        attempts = []
        while utc_now().timestamp() < start + 15:
            try:
                resolution = acquirer.resolve_market_slug("btc-updown-5m-" + str(start), "market")
                store_raw_slug_resolution(resolution, directory)
                bundle = acquirer.acquire_market_bundle(resolution["resolved_market_id"])
                store_raw_bundle(bundle, directory)
                spec = check_market(bundle, start, plan)
                break
            except ContractError:
                raise  # Terms/state mismatch is not a transient discovery failure.
            except Exception as exc:
                attempts.append({"at_utc": utc_text(utc_now()), "error_type": type(exc).__name__})
                time.sleep(5)
        result["discovery_failures"] = attempts
        if bundle is None or utc_now().timestamp() >= start + 30:
            result["status"] = "missed_discovery_window"
            return
        result["capture_started_at_utc"] = utc_text(utc_now())
        result["late_start"] = utc_now().timestamp() > start
        result["raw_bundle_sha256"] = bundle["bundle_sha256"]
        market_id = bundle["market_id_requested"]

        def checkpoint(label):
            try:
                artifact = acquirer.acquire_market_settlement(market_id)
                path = store_raw_settlement(artifact, directory)
                result["metadata_checkpoints"].append({"label": label, "file": path.name})
            except Exception as exc:
                result["metadata_checkpoints"].append({"label": label, "error_type": type(exc).__name__})

        def periodic():
            while not done.wait(60):
                checkpoint("periodic")

        checkpoint_thread = threading.Thread(target=periodic, daemon=True)
        checkpoint_thread.start()
        log = directory / "stream.ndjson"
        result["stream_summary"] = collect_market_stream(bundle, spec, log)
        result["verification"] = verify_stream_log(log)
        done.set()
        checkpoint_thread.join()
        checkpoint("final")
        # A single bounded follow-up is evidence, not a promise of final settlement.
        time.sleep(max(0, min(120, start + 420 - utc_now().timestamp())))
        checkpoint("postclose_120s")
        result["status"] = "observed_" + result["stream_summary"]["status"]
    except Exception as exc:
        result["status"] = "failed"
        result["error_type"] = type(exc).__name__
        result["error"] = str(exc)[:300]
        if (directory / "stream.ndjson").exists():
            try:
                result["verification"] = verify_stream_log(directory / "stream.ndjson")
            except Exception as verification_error:
                result["verification_error_type"] = type(verification_error).__name__
    finally:
        done.set()
        if checkpoint_thread is not None:
            checkpoint_thread.join()
        result["finished_at_utc"] = utc_text(utc_now())
        result["result_sha256"] = payload_hash(result)
        persist(directory / "result.json", result)
        print(json.dumps(result), flush=True)


def run_pilot(plan, root):
    validate_plan(plan)
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    # Exclusive declaration prevents replaying a cohort after a restart.
    persist(root / "pilot.json", plan)
    futures = []
    with ThreadPoolExecutor(max_workers=2) as workers:
        for start in plan["market_starts"]:
            while utc_now().timestamp() < start - 30:
                time.sleep(max(0, min(1, start - 30 - utc_now().timestamp())))
            if not spool_ok(root, plan):
                raise ContractError("spool/free-space budget exhausted; stop without deleting evidence")
            futures.append(workers.submit(observe_window, start, plan, root))
        for future in futures:
            future.result()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    declare = sub.add_parser("declare")
    declare.add_argument("--first-start", type=int, required=True)
    declare.add_argument("--markets", type=int, default=6)
    declare.add_argument("--output", required=True)
    run = sub.add_parser("run")
    run.add_argument("plan")
    run.add_argument("--root", required=True)
    args = parser.parse_args()
    if args.command == "declare":
        plan = pilot_plan(args.first_start, args.markets)
        persist(args.output, plan)
        print(json.dumps(plan, indent=2))
    else:
        run_pilot(json.loads(Path(args.plan).read_text()), args.root)


if __name__ == "__main__":
    main()
